export const CONSTANTS = {
  // Chunking
  MAX_CHUNK_WORDS: 600,
  CHUNK_OVERLAP_WORDS: 80,
  HEADING_SIZE_MULTIPLIER: 1.2,
  MAX_HEADING_WORDS: 12,
  MIN_CHUNK_CHARS: 30,

  // Embeddings
  EMBEDDING_MODEL: "text-embedding-3-small" as const,
  EMBEDDING_DIMENSIONS: 1536,
  EMBEDDING_BATCH_SIZE: 100,

  // Clustering
  UMAP_N_COMPONENTS: 15,
  UMAP_N_NEIGHBORS: 10,
  HDBSCAN_MIN_CLUSTER_SIZE: 3,
  TOPIC_EDGE_THRESHOLD: 0.45,

  // Retrieval
  VECTOR_SEARCH_LIMIT: 20,
  KEYWORD_SEARCH_LIMIT: 15,
  GRAPH_HOP_WEIGHT_THRESHOLD: 0.5,
  RERANK_TOP_K: 8,
  COHERE_RERANK_MODEL: "rerank-english-v3.0",

  // LLM
  OPENROUTER_CHAT_MODEL: "openai/gpt-oss-120b" as const,
  OPENROUTER_MAX_TOKENS: 512,

  // Polling
  STATUS_POLL_INTERVAL_MS: 2500,
} as const;
